services:
  qdrant:
    image: qdrant/qdrant:v1.9.2
    container_name: rag_db
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: always
